language: node_js
node_js:
  - "0.10"

before_install:

install:
  - npm install
  - node_modules/protractor/bin/webdriver-manager update --standalone

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - nohup bash -c "webdriver-manager start 2>&1 &"
  - npm start &

script:
  - node_modules/.bin/jspm install
  - node_modules/gulp/bin/gulp.js dev-no-watch
  - node_modules/protractor/bin/protractor protractor.conf.js

cache:
  directories:
    - node_modules
    - jspm_packages
